### ISSUE TITLE
Long title will make the forum unusable

### ISSUE THREAD

**Issue by ZENG-Zhuo** [gcivil-nyu-org/fall24-monday-team2#135]
Description: I created a view long posing, the forum is not usable.

Details requested by TA are as below:

Account Used:
Username: team1_admin
Password: team1_admin

Steps Followed:
(a) Go to forum page, and create a new discussion with a super long title.
(b) Then go back to forum page
![Screenshot 2024-11-21 192032](https://github.com/user-attachments/assets/0fc02dd4-ee67-4251-ac0a-e318ee6e7445)

Page URL: http://fiton-dev-without-template.us-west-2.elasticbeanstalk.com/forum/

Expected: I should be able to see all information even with long title.

**Comment by ander9991** [comment]
Nice catch! We will either limit the length of the title or make it go to the next time. First option is more feasable.

**Comment by ZENG-Zhuo** [comment]
And I can see the whole description as well if its long.
![image](https://github.com/user-attachments/assets/41f9a95c-90e3-4baa-bc12-47303817b830)

**Comment by ander9991** [comment]
Bug has been resolved. Thank you!
