### ISSUE TITLE
Failed to filter threads by date. (Testing Party)

### ISSUE THREAD

**Issue by wbw2002** [gcivil-nyu-org/fall24-monday-team2#137]
I'm using Team 5 account. 
I logged in and explored to the Forums part, and tried to filter the threads by date. When the first time I was selecting from *** to *** and clicking "Apply Filters" button, it just showed nothing. It seems that I had click twice to make the results appear. And the date filter will change back to mm/dd/yy immediately after clicking on “Apply Filters” button. Maybe this point can be fixed to keep the date filter.
Thank you! That's a great app!

**Comment by wbw2002** [comment]
![Screenshot 2024-11-21 220241](https://github.com/user-attachments/assets/f67ad4c3-237f-4dbd-ae6c-ff6234fd8c7a)

**Comment by ander9991** [comment]
> ![Screenshot 2024-11-21 220241](https://private-user-images.githubusercontent.com/130182996/388785813-f67ad4c3-237f-4dbd-ae6c-ff6234fd8c7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMDc4NTIsIm5iZiI6MTczMjMwNzU1MiwicGF0aCI6Ii8xMzAxODI5OTYvMzg4Nzg1ODEzLWY2N2FkNGMzLTIzN2YtNGRiZC1hZTZjLWZmNjIzNGZkOGM3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQyMDMyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZThmMzQxMDFkNTQ5MzA2ZGQyNGY4NjY5YmFiYzVmM2RmOTNiZjY1YzFmNmIwMGVkOWEzN2FmYzExMDY1ZWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GyJemTJ3TWSAUXkb41Hvt6LQhUT0vF9tzvjQGNuKOuo)

Hi @wbw2002 

We are unable to replicate the issue you experienced (date filters) as it works fine for us.  As for "date filter will change back to mm/dd/yy immediately after clicking on “Apply Filters” button", we are aware of this and it was mentioned in the wiki testing party document that this is the behavior we are expecting at the moment, but will refine it down the line if we have time. 

Could you either show us in a meeting or record a video of the date filtering not working properly? Thanks!

![image](https://github.com/user-attachments/assets/ee5e09d6-8d66-40f1-8039-40270b1a59c4)
